ALTER TABLE patients
    ADD COLUMN email VARCHAR(255) NOT NULL,
    ADD COLUMN telephone_number VARCHAR(20) NOT NULL,
    ADD COLUMN street VARCHAR(255),
    ADD COLUMN neighborhood VARCHAR(255),
    ADD COLUMN zip_code VARCHAR(8) NOT NULL,
    ADD COLUMN city VARCHAR(255) NOT NULL,
    ADD COLUMN state VARCHAR(255) NOT NULL,
    ADD COLUMN number VARCHAR(20),
    ADD COLUMN address_complement VARCHAR(255),
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;